from . import g2p_bank_bank
from . import g2p_bank_branch
from . import g2p_cash_grant_detail
from . import g2p_crop
from . import g2p_crop_category
from . import g2p_crop_type
from . import g2p_cultivation_details
from . import g2p_damage
from . import g2p_damage_stage
from . import g2p_damage_type
from . import g2p_district
from . import g2p_divisional_secreteriats
from . import g2p_flood_damage_subsidy
from . import g2p_gn_division
from . import g2p_agrarian_research_production_assistant
from . import g2p_agrarian_service_center
from . import g2p_gn_division
from . import g2p_land_details
from . import g2p_res_partner
from . import g2p_res_partner_bank
from . import g2p_region
from . import g2p_season
from . import g2p_subsidy_detail
from . import g2p_status
