{
    "name": "OpenG2P Farmer Registry",
    "category": "G2P",
    "version": "17.0.1.0.0",
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": [
        'web',
        'muk_web_theme',
        'g2p_registry_id_deduplication', 'g2p_social_registry',
        'g2p_agent_portal_base',
        'g2p_social_registry_theme', 'g2p_auth_id_oidc',
        'g2p_documents', 'g2p_superset_dashboard', 'mts_connector',
        'g2p_odk_importer',
        'mail', 'g2p_bank'
    ],
    "data": [
        'security/ir.model.access.csv',
        "data/locations.xml",
        "data/res_lang.xml",
        "data/sequence.xml",
        'views/g2p_region_views.xml',
        'views/g2p_divisional_secreteriats_views.xml',
        'views/g2p_district_views.xml',
        'views/g2p_agrarian_service_center_views.xml',
        'views/g2p_agrarian_research_production_assistant_views.xml',
        'views/g2p_gn_division_views.xml',
        'views/g2p_bank_bank_views.xml',
        'views/g2p_bank_branch_views.xml',
        'views/main_view_inherit.xml',
        'views/farmer_form_simplified.xml',
        'views/land_details_view.xml',
        'views/g2p_crop_category_views.xml',
        'views/g2p_crop_type_views.xml',
        'views/g2p_crop_views.xml',
        'views/g2p_cultivation_details_views.xml',
        'views/g2p_cash_grant_detail_views.xml',
        'views/g2p_flood_damage_subsidy_views.xml',
    ],
    "assets": {
        'web.assets_backend': [
            'g2p_farmer_registry/static/css/custom_home.css',
            'g2p_farmer_registry/static/css/farmer_theme.css',
            'g2p_farmer_registry/static/src/scss/farmer_menu.scss',
            'g2p_farmer_registry/static/src/js/custom_home.js',
            'g2p_farmer_registry/static/src/xml/menu_kanban_view_changes.xml'
        ],
    },
    "demo": [],
    "images": [],
    "installable": True,
    'uninstall_hook': 'uninstall_hook',
}
